### ISSUE TITLE
Order page does not properly update numbers in inventory nor have much user interaction

### ISSUE THREAD

**Issue by fieryshadow** [fieryshadow/MaryKayInventoryApp#1]
Need to connect to our custom list adapter with added onClick functionality.

**Comment by fieryshadow** [comment]
Need a list of products. When a product is clicked, the number of product which gets you back up to the highest number in inventory history gets put on the order list. Tapping again brings up a dialog to manually enter in a value, and swiping the product away sets its order amount to zero.

**Comment by harstong** [comment]
Order page just needs to make a receipt when you click the submit button.  It is now updating correctly for what the default order should be.  It would be nice if it updated the total at the bottom of the page for each time something changes.
